font_family MesloLGS NF
bold_font MesloLGS NF Bold
italic_font MesloLGS NF Italic
bold_italic_font MesloLGS NF Bold Italic

shell /usr/bin/zsh

# Copiar y pegar
copy_on_select yes
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

# Clic derecho = pegar desde portapapeles
mouse_map right press paste_from_clipboard

# =========================
# Catppuccin Mocha
# =========================

foreground              #cdd6f4
background              #11111b
selection_foreground    #11111b
selection_background    #f5e0e6

cursor                  #f5e0e6
cursor_text_color       #11111b

url_color               #89b4fa

# Negro
color0                  #45475a
color8                  #585b70

# Rojo
color1                  #f38ba8
color9                  #f38ba8

# Verde
color2                  #a6e3a1
color10                 #a6e3a1

# Amarillo
color3                  #f9e2af
color11                 #f9e2af

# Azul
color4                  #89b4fa
color12                 #89b4fa

# Magenta
color5                  #f5c2e7
color13                 #f5c2e7

# Cyan
color6                  #94e2d5
color14                 #94e2d5

# Blanco
color7                  #bac2de
color15                 #a6adc8


# =========================
# Transparencia
# =========================

background_opacity 0.88
